# Generated by Django 5.2.12 on 2026-05-29 17:10

import django.db.models.deletion
import django.utils.timezone
import newsroom.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsroom_activity_events', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Подія активності',
                'verbose_name_plural': 'Події активності',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва кластера')),
                ('summary', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsroom_clusters', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Кластер',
                'verbose_name_plural': 'Кластери',
                'ordering': ['-last_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('url', models.URLField(max_length=500, verbose_name='URL матеріалу')),
                ('normalized_url', models.URLField(blank=True, db_index=True, max_length=500, verbose_name='Нормалізований URL')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Хеш змісту')),
                ('content', models.TextField(blank=True, verbose_name='Повний текст')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processed', 'Оброблене'), ('clustered', 'У кластері'), ('rejected', 'Відхилене')], default='new', max_length=16, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубліковано')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Отримано')),
                ('relevance_score', models.PositiveSmallIntegerField(default=0, verbose_name='Оцінка релевантності')),
                ('relevance_reason', models.CharField(blank=True, max_length=255, verbose_name='Пояснення релевантності')),
                ('manual_relevance_approved', models.BooleanField(default=False, verbose_name='Схвалено редактором після ШІ')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В обраному')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsroom_articles', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsroom.cluster', verbose_name='Кластер')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва шаблону')),
                ('description', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('prompt_text', models.TextField(verbose_name='Інструкція для генерації')),
                ('example_texts', models.JSONField(blank=True, default=list, verbose_name='Приклади текстів')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('archived', 'Архів')], default='active', max_length=16, verbose_name='Статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsroom_content_templates', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Шаблон контенту',
                'verbose_name_plural': 'Шаблони контенту',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('target_length', models.CharField(choices=[('short', 'Коротка'), ('medium', 'Середня'), ('long', 'Довга')], default='medium', max_length=16, verbose_name='Цільова довжина')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Згенеровано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('content_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='newsroom.contenttemplate', verbose_name='Шаблон контенту')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsroom_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
                ('source_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_drafts', to='newsroom.article', verbose_name='Вихідна стаття')),
            ],
            options={
                'verbose_name': 'Чернетка',
                'verbose_name_plural': 'Чернетки',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема моніторингу')),
                ('keywords', models.TextField(verbose_name='Ключові слова та фрази')),
                ('time_window', models.CharField(choices=[('24h', 'Остання доба'), ('7d', 'Останній тиждень'), ('30d', 'Останній місяць'), ('date', 'Конкретна дата'), ('range', 'Період за датами')], default='24h', max_length=8, verbose_name='Часовий фільтр')),
                ('exact_date', models.DateField(blank=True, null=True, verbose_name='Конкретна дата')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата від')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата до')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('archived', 'Архів')], default='active', max_length=16, verbose_name='Статус')),
                ('run_state', models.CharField(choices=[('idle', 'Готова'), ('running', 'Виконується'), ('error', 'Помилка')], default='idle', max_length=16, verbose_name='Стан запуску')),
                ('run_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Початок запуску')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name='Запит на зупинку')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Останній запуск')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsroom_topics', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Тема моніторингу',
                'verbose_name_plural': 'Теми моніторингу',
                'ordering': ['topic'],
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='monitoring_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='newsroom.monitoringtopic', verbose_name='Тема моніторингу'),
        ),
        migrations.AddField(
            model_name='article',
            name='monitoring_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsroom.monitoringtopic', verbose_name='Тема моніторингу'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('type', models.CharField(choices=[('site', 'Сайт'), ('telegram', 'Telegram')], default='site', max_length=16, verbose_name='Тип')),
                ('status', models.CharField(choices=[('active', 'Активне'), ('archived', 'Архів')], default='active', max_length=16, verbose_name='Статус')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категорія')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Останній запуск моніторингу')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsroom_sources', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Джерело',
                'verbose_name_plural': 'Джерела',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='monitoringtopic',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='monitoring_topics', to='newsroom.source', verbose_name='Джерела'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsroom.source', verbose_name='Джерело'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_time_window', models.CharField(choices=[('24h', 'Остання доба'), ('7d', 'Останній тиждень'), ('30d', 'Останній місяць'), ('date', 'Конкретна дата'), ('range', 'Період за датами')], default='24h', max_length=8, verbose_name='Типовий часовий фільтр')),
                ('default_draft_length', models.CharField(choices=[('short', 'Коротка'), ('medium', 'Середня'), ('long', 'Довга')], default='medium', max_length=16, verbose_name='Типова довжина чернетки')),
                ('openai_model', models.CharField(default=newsroom.models.default_openai_model, max_length=100, verbose_name='Модель OpenAI')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsroom_settings', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Налаштування користувача',
                'verbose_name_plural': 'Налаштування користувачів',
            },
        ),
        migrations.AddConstraint(
            model_name='contenttemplate',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_content_template_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('owner', 'url'), name='unique_source_url_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='monitoringtopic',
            constraint=models.UniqueConstraint(fields=('owner', 'topic'), name='unique_monitoring_topic_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('owner', 'monitoring_topic', 'url'), name='unique_article_url_per_topic_owner'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('relevance_score__gte', 0), ('relevance_score__lte', 100)), name='article_relevance_score_range'),
        ),
    ]
